name: Bit Rot - Windows

on:
  push: { tags: ['v*'] }
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Windows
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install cryptography

      - name: Generate Signing Certificate
        run: python bitrot/tools/windows_certificate.py cert.pfx

      - name: Build with Nuitka
        run: |
          nuitka --standalone `
          --assume-yes-for-downloads `
          --output-dir=./build `
          --windows-console-mode=disable `
          --windows-icon-from-ico=./bitrot/data.rot/icons/favicon.ico `
          bitrot/bitrot.py

      - name: Sign Executable
        shell: pwsh
        run: |
          $signtool = Get-ChildItem -Path "C:\Program Files (x86)\Windows Kits\10\bin" -Recurse | 
                      Where-Object { $_.FullName -like "*\x64\signtool.exe" } | 
                      Select-Object -First 1
          & $signtool.FullName sign /f cert.pfx /p "bitrot&Certificate@Windows912026" /tr http://timestamp.digicert.com /td sha256 /fd sha256 "build\bitrot.dist\bitrot.exe"

      - name: Package Game
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path release
          Copy-Item -Path "build\bitrot.dist\*" -Destination "release" -Recurse -Force
          Copy-Item -Path "bitrot\data.rot" -Destination "release" -Recurse -Force

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitrot-windows
          path: bitrot_windows.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bitrot_windows.zip
          generate_release_notes: true