name: Bit Rot - Linux

on:
  push: { tags: ['v*'] }
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install System Dependencies
        run: sudo apt-get update && sudo apt-get install -y patchelf ccache zip

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          nuitka --standalone \
          --assume-yes-for-downloads \
          --output-dir=./build \
          --static-libpython=yes \
          --include-data-dir=bitrot/data.rot=data.rot \
          bitrot/bitrot.py

      - name: Package Game
        run: |
          mkdir release
          cp -r build/bitrot.dist/* release/
          cp -r bitrot/data.rot release/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitrot-linux
          path: bitrot_linux.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bitrot_linux.zip
          generate_release_notes: true