name: Bit Rot - macOS

on:
  push: { tags: ['v*'] }
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build macOS
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python Dependencies
        run: pip install -r requirements.txt

      - name: Build with Nuitka
        run: |
          nuitka --standalone \
          --macos-create-app-bundle \
          --macos-app-icon=./bitrot/data.rot/icons/favicon.icns \
          --assume-yes-for-downloads \
          --output-dir=./build \
          --static-libpython=yes \
          bitrot/bitrot.py

      - name: Package Game
        run: |
          mkdir release
          cp -r build/bitrot.app bitrot_macos/
          cp -r bitrot/data.rot bitrot_macos/

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bitrot-macos
          path: bitrot_macos/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: bitrot_macos.zip
          generate_release_notes: true